name: Metrics (LeetCode)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "none"
          filename: metrics.leetcode.svg
          output_dir: metrics_renders
          plugin_leetcode: yes
          plugin_leetcode_user: firkraagg
          plugin_leetcode_sections: solved, skills, recent

  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "none"
          filename: metrics.isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
